name: IRM

on:
  pull_request:
    paths:
      - "src/irm/**"
      - "test/forge/irm/**"
      - "test/forge/integration/AccrueInterestIntegrationTest.sol"
      - "foundry.toml"
      - "package.json"
      - ".github/workflows/irm.yml"
  push:
    branches:
      - main
    paths:
      - "src/irm/**"
      - "test/forge/irm/**"
      - "test/forge/integration/AccrueInterestIntegrationTest.sol"
      - "foundry.toml"
      - "package.json"
      - ".github/workflows/irm.yml"
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}-${{ github.event_name }}
  cancel-in-progress: true

jobs:
  irm-tests:
    runs-on: ubuntu-latest
    timeout-minutes: 60
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Install Foundry
        uses: foundry-rs/foundry-toolchain@v1

      - name: Log IRM Seed
        run: 'echo "IRM seed: 0x${{ github.event.pull_request.base.sha || github.sha }}"'

      - name: Run IRM Forge tests
        run: yarn -s test:forge:irm
        env:
          FOUNDRY_PROFILE: test-irm
          FOUNDRY_FUZZ_SEED: 0x${{ github.event.pull_request.base.sha || github.sha }}
